language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install Django
    - export PYTHONPATH=.

script: python setup.py test

matrix:
  exclude:
    - python: "3.5"
