language: python

python:
    # - "2.7"
    - "3.4"
    - "3.5"

env:
    # - DJANGO="1.7.11"
    # - DJANGO="1.8.12"
    - DJANGO="1.9.5"

install:
    - pip install Django==$DJANGO
    - export PYTHONPATH=.

script: python setup.py test

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="1.7.11"
    - python: "3.4"
      env: DJANGO="1.7.11"
    - python: "2.7"
      env: DJANGO="1.7.11"
